# This file was generated by GoReleaser. DO NOT EDIT.
class Aspic < Formula
  desc "CLI for Aspic projects"
  homepage "http://aspic.ithings.ch"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thpham/aspic/releases/download/v0.1/aspic_0.1_darwin_amd64.tar.gz"
    sha256 "46ab02a0b2c46d7615d884011c3f8bca9af3c81e5658884df3f5b66d0f41113a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thpham/aspic/releases/download/v0.1/aspic_0.1_linux_amd64.tar.gz"
      sha256 "2c9292f178943e77d9345667af92edabfb74e0c4f3cbbd617e186e3d34154179"
    end
  end
  
  depends_on "go"

  def install
    bin.install "aspic"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/aspic -h"
  end
end
