# This file was generated by GoReleaser. DO NOT EDIT.
class Aspic < Formula
  desc "CLI for Aspic projects"
  homepage "http://aspic.ithings.ch"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thpham/aspic/releases/download/v0.1/aspic_0.1_darwin_amd64.tar.gz"
    sha256 "9e4345972fc57905222cfbcf27fae6773fd2e0af6ab8c03f30f6cd7ccae82cf5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thpham/aspic/releases/download/v0.1/aspic_0.1_linux_amd64.tar.gz"
      sha256 "f235bb5980d475ccc46d7c0457b8111ccf3ecfb2c3288e6368f1a614fe08f4f6"
    end
  end
  
  depends_on "go"

  def install
    bin.install "aspic"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/aspic -h"
  end
end
